### ISSUE TITLE
Permission Errors when Starting the Container and When Updating

### ISSUE THREAD

**Issue by freespiritstays** [MekayelAnik/ispyagentdvr-docker#28]
I recently updated my image and now I am getting these errors. How do I fix it?

cat: /usr/bin/share/base-image-timestamp: No such file or directory
This docker image was built at: Sat Aug 24 20:08:20 +06 2024 : Bangladesh Time (UTC+06)
This Container was started on: Wed Aug 28 18:54:49 America 2024
usermod: no changes
Failed to create secure directory (/root/.config/pulse): Permission denied
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
/AgentDVR/agent-update.sh: line 1: #!/bin/bash: No such file or directory
/AgentDVR/agent-update.sh: line 20: systemctl: command not found
Service not found
Reading package lists...
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)
Installing update
/AgentDVR/agent-update.sh: line 34: unzip: command not found
Restarting Agent
Failed to create secure directory (/root/.config/pulse): Permission denied
Failed to create a UDP socket bound at 0.0.0.0:3478
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories

**Comment by MekayelAnik** [comment]
You can't update the image using update script in the docker which undermines the purpose of docker image.
When a new version of docker is available, please download the or use watchtower for automatic docker image update.
Now,
- `cat: /usr/bin/share/base-image-timestamp`
is not a breaking issue. But, will be be fixed in the next release (which will take place today), INSHALLAH.

- `Failed to create secure directory (/root/.config/pulse): Permission denied`
is a pulse audio software issue. I am tring to fix it, but I don't have any control over it. The problem lies in the 'Pulse Audio' source code, As I have seen.

Regards
