### ISSUE TITLE
Container start aborting on PI5

### ISSUE THREAD

**Issue by Th3s3cond** [MekayelAnik/ispyagentdvr-docker#7]
Hi,

i have the problem that the container wont start.

![image](https://github.com/MekayelAnik/ispyagentdvr-docker/assets/149875411/031a94ee-9970-41f0-aae0-1a6e5c825f36)

Anyone an Idea why?

Cheers Th3s3cond

**Comment by MekayelAnik** [comment]
After a long inspection, sorry to say I didn't find any problem in the image. Though I don't have a Raspi-5, but the benefit of docker is, it is machine independent and platform independent (sort of).
I think there are some weird issues in the docker engine of the Raspbian for raspi-5 or Raspbian itself (the later is more likely). That's why you are facing the unusual problems.
Can you please use the [Ubuntu](https://ubuntu.com/download/raspberry-pi) for Raspi-5? I would suggest [dietpi](https://dietpi.com/#downloadinfo) as I find it best for ARM SBCs, but it's not out yet for the raspi-5.
I have seen that the Ubuntu is far better and much more bug free for Raspi-5. I hope the OS solves your problem.
Please leave a feedback if you do test out the Ubuntu.
Regards

**Comment by Th3s3cond** [comment]
fyi

i set up a rpi4 with the same conditions like on the rpi5 an the image will work fine.
Actually i had no idee where´s the problem, if i found it i give an short feedback.

Cheers
